// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_UDPMESSAGES_UDP_COMMUNICATION_H_
#define FLATBUFFERS_GENERATED_UDPMESSAGES_UDP_COMMUNICATION_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 5 &&
              FLATBUFFERS_VERSION_REVISION == 26,
             "Non-compatible flatbuffers version included");

namespace udp_communication {

struct ControlCmd;
struct ControlCmdBuilder;

struct Heartbeat;
struct HeartbeatBuilder;

struct SensorData;
struct SensorDataBuilder;

struct StatusReport;
struct StatusReportBuilder;

struct Pc2RobotWrapper;
struct Pc2RobotWrapperBuilder;

struct Robot2PcWrapper;
struct Robot2PcWrapperBuilder;

enum Pc2RobotMsg : uint8_t {
  Pc2RobotMsg_NONE = 0,
  Pc2RobotMsg_ControlCmd = 1,
  Pc2RobotMsg_Heartbeat = 2,
  Pc2RobotMsg_MIN = Pc2RobotMsg_NONE,
  Pc2RobotMsg_MAX = Pc2RobotMsg_Heartbeat
};

inline const Pc2RobotMsg (&EnumValuesPc2RobotMsg())[3] {
  static const Pc2RobotMsg values[] = {
    Pc2RobotMsg_NONE,
    Pc2RobotMsg_ControlCmd,
    Pc2RobotMsg_Heartbeat
  };
  return values;
}

inline const char * const *EnumNamesPc2RobotMsg() {
  static const char * const names[4] = {
    "NONE",
    "ControlCmd",
    "Heartbeat",
    nullptr
  };
  return names;
}

inline const char *EnumNamePc2RobotMsg(Pc2RobotMsg e) {
  if (::flatbuffers::IsOutRange(e, Pc2RobotMsg_NONE, Pc2RobotMsg_Heartbeat)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesPc2RobotMsg()[index];
}

template<typename T> struct Pc2RobotMsgTraits {
  static const Pc2RobotMsg enum_value = Pc2RobotMsg_NONE;
};

template<> struct Pc2RobotMsgTraits<udp_communication::ControlCmd> {
  static const Pc2RobotMsg enum_value = Pc2RobotMsg_ControlCmd;
};

template<> struct Pc2RobotMsgTraits<udp_communication::Heartbeat> {
  static const Pc2RobotMsg enum_value = Pc2RobotMsg_Heartbeat;
};

bool VerifyPc2RobotMsg(::flatbuffers::Verifier &verifier, const void *obj, Pc2RobotMsg type);
bool VerifyPc2RobotMsgVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

enum Robot2PcMsg : uint8_t {
  Robot2PcMsg_NONE = 0,
  Robot2PcMsg_SensorData = 1,
  Robot2PcMsg_StatusReport = 2,
  Robot2PcMsg_MIN = Robot2PcMsg_NONE,
  Robot2PcMsg_MAX = Robot2PcMsg_StatusReport
};

inline const Robot2PcMsg (&EnumValuesRobot2PcMsg())[3] {
  static const Robot2PcMsg values[] = {
    Robot2PcMsg_NONE,
    Robot2PcMsg_SensorData,
    Robot2PcMsg_StatusReport
  };
  return values;
}

inline const char * const *EnumNamesRobot2PcMsg() {
  static const char * const names[4] = {
    "NONE",
    "SensorData",
    "StatusReport",
    nullptr
  };
  return names;
}

inline const char *EnumNameRobot2PcMsg(Robot2PcMsg e) {
  if (::flatbuffers::IsOutRange(e, Robot2PcMsg_NONE, Robot2PcMsg_StatusReport)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesRobot2PcMsg()[index];
}

template<typename T> struct Robot2PcMsgTraits {
  static const Robot2PcMsg enum_value = Robot2PcMsg_NONE;
};

template<> struct Robot2PcMsgTraits<udp_communication::SensorData> {
  static const Robot2PcMsg enum_value = Robot2PcMsg_SensorData;
};

template<> struct Robot2PcMsgTraits<udp_communication::StatusReport> {
  static const Robot2PcMsg enum_value = Robot2PcMsg_StatusReport;
};

bool VerifyRobot2PcMsg(::flatbuffers::Verifier &verifier, const void *obj, Robot2PcMsg type);
bool VerifyRobot2PcMsgVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

struct ControlCmd FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ControlCmdBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_LINEAR_VEL = 4,
    VT_ANGULAR_VEL = 6,
    VT_MODE = 8
  };
  float linear_vel() const {
    return GetField<float>(VT_LINEAR_VEL, 0.0f);
  }
  float angular_vel() const {
    return GetField<float>(VT_ANGULAR_VEL, 0.0f);
  }
  int32_t mode() const {
    return GetField<int32_t>(VT_MODE, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<float>(verifier, VT_LINEAR_VEL, 4) &&
           VerifyField<float>(verifier, VT_ANGULAR_VEL, 4) &&
           VerifyField<int32_t>(verifier, VT_MODE, 4) &&
           verifier.EndTable();
  }
};

struct ControlCmdBuilder {
  typedef ControlCmd Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_linear_vel(float linear_vel) {
    fbb_.AddElement<float>(ControlCmd::VT_LINEAR_VEL, linear_vel, 0.0f);
  }
  void add_angular_vel(float angular_vel) {
    fbb_.AddElement<float>(ControlCmd::VT_ANGULAR_VEL, angular_vel, 0.0f);
  }
  void add_mode(int32_t mode) {
    fbb_.AddElement<int32_t>(ControlCmd::VT_MODE, mode, 0);
  }
  explicit ControlCmdBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ControlCmd> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ControlCmd>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ControlCmd> CreateControlCmd(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    float linear_vel = 0.0f,
    float angular_vel = 0.0f,
    int32_t mode = 0) {
  ControlCmdBuilder builder_(_fbb);
  builder_.add_mode(mode);
  builder_.add_angular_vel(angular_vel);
  builder_.add_linear_vel(linear_vel);
  return builder_.Finish();
}

struct Heartbeat FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef HeartbeatBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TIMESTAMP = 4,
    VT_PC_STATUS = 6
  };
  int64_t timestamp() const {
    return GetField<int64_t>(VT_TIMESTAMP, 0);
  }
  bool pc_status() const {
    return GetField<uint8_t>(VT_PC_STATUS, 0) != 0;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int64_t>(verifier, VT_TIMESTAMP, 8) &&
           VerifyField<uint8_t>(verifier, VT_PC_STATUS, 1) &&
           verifier.EndTable();
  }
};

struct HeartbeatBuilder {
  typedef Heartbeat Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_timestamp(int64_t timestamp) {
    fbb_.AddElement<int64_t>(Heartbeat::VT_TIMESTAMP, timestamp, 0);
  }
  void add_pc_status(bool pc_status) {
    fbb_.AddElement<uint8_t>(Heartbeat::VT_PC_STATUS, static_cast<uint8_t>(pc_status), 0);
  }
  explicit HeartbeatBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Heartbeat> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Heartbeat>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Heartbeat> CreateHeartbeat(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int64_t timestamp = 0,
    bool pc_status = false) {
  HeartbeatBuilder builder_(_fbb);
  builder_.add_timestamp(timestamp);
  builder_.add_pc_status(pc_status);
  return builder_.Finish();
}

struct SensorData FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SensorDataBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TEMPERATURE = 4,
    VT_DISTANCE = 6,
    VT_TIMESTAMP = 8
  };
  float temperature() const {
    return GetField<float>(VT_TEMPERATURE, 0.0f);
  }
  float distance() const {
    return GetField<float>(VT_DISTANCE, 0.0f);
  }
  int64_t timestamp() const {
    return GetField<int64_t>(VT_TIMESTAMP, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<float>(verifier, VT_TEMPERATURE, 4) &&
           VerifyField<float>(verifier, VT_DISTANCE, 4) &&
           VerifyField<int64_t>(verifier, VT_TIMESTAMP, 8) &&
           verifier.EndTable();
  }
};

struct SensorDataBuilder {
  typedef SensorData Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_temperature(float temperature) {
    fbb_.AddElement<float>(SensorData::VT_TEMPERATURE, temperature, 0.0f);
  }
  void add_distance(float distance) {
    fbb_.AddElement<float>(SensorData::VT_DISTANCE, distance, 0.0f);
  }
  void add_timestamp(int64_t timestamp) {
    fbb_.AddElement<int64_t>(SensorData::VT_TIMESTAMP, timestamp, 0);
  }
  explicit SensorDataBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SensorData> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SensorData>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SensorData> CreateSensorData(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    float temperature = 0.0f,
    float distance = 0.0f,
    int64_t timestamp = 0) {
  SensorDataBuilder builder_(_fbb);
  builder_.add_timestamp(timestamp);
  builder_.add_distance(distance);
  builder_.add_temperature(temperature);
  return builder_.Finish();
}

struct StatusReport FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef StatusReportBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_BATTERY = 4,
    VT_ERROR_CODE = 6,
    VT_TIMESTAMP = 8
  };
  float battery() const {
    return GetField<float>(VT_BATTERY, 0.0f);
  }
  int32_t error_code() const {
    return GetField<int32_t>(VT_ERROR_CODE, 0);
  }
  int64_t timestamp() const {
    return GetField<int64_t>(VT_TIMESTAMP, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<float>(verifier, VT_BATTERY, 4) &&
           VerifyField<int32_t>(verifier, VT_ERROR_CODE, 4) &&
           VerifyField<int64_t>(verifier, VT_TIMESTAMP, 8) &&
           verifier.EndTable();
  }
};

struct StatusReportBuilder {
  typedef StatusReport Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_battery(float battery) {
    fbb_.AddElement<float>(StatusReport::VT_BATTERY, battery, 0.0f);
  }
  void add_error_code(int32_t error_code) {
    fbb_.AddElement<int32_t>(StatusReport::VT_ERROR_CODE, error_code, 0);
  }
  void add_timestamp(int64_t timestamp) {
    fbb_.AddElement<int64_t>(StatusReport::VT_TIMESTAMP, timestamp, 0);
  }
  explicit StatusReportBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<StatusReport> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<StatusReport>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<StatusReport> CreateStatusReport(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    float battery = 0.0f,
    int32_t error_code = 0,
    int64_t timestamp = 0) {
  StatusReportBuilder builder_(_fbb);
  builder_.add_timestamp(timestamp);
  builder_.add_error_code(error_code);
  builder_.add_battery(battery);
  return builder_.Finish();
}

struct Pc2RobotWrapper FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef Pc2RobotWrapperBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MSG_TYPE = 4,
    VT_MSG = 6
  };
  udp_communication::Pc2RobotMsg msg_type() const {
    return static_cast<udp_communication::Pc2RobotMsg>(GetField<uint8_t>(VT_MSG_TYPE, 0));
  }
  const void *msg() const {
    return GetPointer<const void *>(VT_MSG);
  }
  template<typename T> const T *msg_as() const;
  const udp_communication::ControlCmd *msg_as_ControlCmd() const {
    return msg_type() == udp_communication::Pc2RobotMsg_ControlCmd ? static_cast<const udp_communication::ControlCmd *>(msg()) : nullptr;
  }
  const udp_communication::Heartbeat *msg_as_Heartbeat() const {
    return msg_type() == udp_communication::Pc2RobotMsg_Heartbeat ? static_cast<const udp_communication::Heartbeat *>(msg()) : nullptr;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_MSG_TYPE, 1) &&
           VerifyOffset(verifier, VT_MSG) &&
           VerifyPc2RobotMsg(verifier, msg(), msg_type()) &&
           verifier.EndTable();
  }
};

template<> inline const udp_communication::ControlCmd *Pc2RobotWrapper::msg_as<udp_communication::ControlCmd>() const {
  return msg_as_ControlCmd();
}

template<> inline const udp_communication::Heartbeat *Pc2RobotWrapper::msg_as<udp_communication::Heartbeat>() const {
  return msg_as_Heartbeat();
}

struct Pc2RobotWrapperBuilder {
  typedef Pc2RobotWrapper Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_msg_type(udp_communication::Pc2RobotMsg msg_type) {
    fbb_.AddElement<uint8_t>(Pc2RobotWrapper::VT_MSG_TYPE, static_cast<uint8_t>(msg_type), 0);
  }
  void add_msg(::flatbuffers::Offset<void> msg) {
    fbb_.AddOffset(Pc2RobotWrapper::VT_MSG, msg);
  }
  explicit Pc2RobotWrapperBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Pc2RobotWrapper> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Pc2RobotWrapper>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Pc2RobotWrapper> CreatePc2RobotWrapper(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    udp_communication::Pc2RobotMsg msg_type = udp_communication::Pc2RobotMsg_NONE,
    ::flatbuffers::Offset<void> msg = 0) {
  Pc2RobotWrapperBuilder builder_(_fbb);
  builder_.add_msg(msg);
  builder_.add_msg_type(msg_type);
  return builder_.Finish();
}

struct Robot2PcWrapper FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef Robot2PcWrapperBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MSG_TYPE = 4,
    VT_MSG = 6
  };
  udp_communication::Robot2PcMsg msg_type() const {
    return static_cast<udp_communication::Robot2PcMsg>(GetField<uint8_t>(VT_MSG_TYPE, 0));
  }
  const void *msg() const {
    return GetPointer<const void *>(VT_MSG);
  }
  template<typename T> const T *msg_as() const;
  const udp_communication::SensorData *msg_as_SensorData() const {
    return msg_type() == udp_communication::Robot2PcMsg_SensorData ? static_cast<const udp_communication::SensorData *>(msg()) : nullptr;
  }
  const udp_communication::StatusReport *msg_as_StatusReport() const {
    return msg_type() == udp_communication::Robot2PcMsg_StatusReport ? static_cast<const udp_communication::StatusReport *>(msg()) : nullptr;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_MSG_TYPE, 1) &&
           VerifyOffset(verifier, VT_MSG) &&
           VerifyRobot2PcMsg(verifier, msg(), msg_type()) &&
           verifier.EndTable();
  }
};

template<> inline const udp_communication::SensorData *Robot2PcWrapper::msg_as<udp_communication::SensorData>() const {
  return msg_as_SensorData();
}

template<> inline const udp_communication::StatusReport *Robot2PcWrapper::msg_as<udp_communication::StatusReport>() const {
  return msg_as_StatusReport();
}

struct Robot2PcWrapperBuilder {
  typedef Robot2PcWrapper Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_msg_type(udp_communication::Robot2PcMsg msg_type) {
    fbb_.AddElement<uint8_t>(Robot2PcWrapper::VT_MSG_TYPE, static_cast<uint8_t>(msg_type), 0);
  }
  void add_msg(::flatbuffers::Offset<void> msg) {
    fbb_.AddOffset(Robot2PcWrapper::VT_MSG, msg);
  }
  explicit Robot2PcWrapperBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Robot2PcWrapper> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Robot2PcWrapper>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Robot2PcWrapper> CreateRobot2PcWrapper(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    udp_communication::Robot2PcMsg msg_type = udp_communication::Robot2PcMsg_NONE,
    ::flatbuffers::Offset<void> msg = 0) {
  Robot2PcWrapperBuilder builder_(_fbb);
  builder_.add_msg(msg);
  builder_.add_msg_type(msg_type);
  return builder_.Finish();
}

inline bool VerifyPc2RobotMsg(::flatbuffers::Verifier &verifier, const void *obj, Pc2RobotMsg type) {
  switch (type) {
    case Pc2RobotMsg_NONE: {
      return true;
    }
    case Pc2RobotMsg_ControlCmd: {
      auto ptr = reinterpret_cast<const udp_communication::ControlCmd *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Pc2RobotMsg_Heartbeat: {
      auto ptr = reinterpret_cast<const udp_communication::Heartbeat *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyPc2RobotMsgVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyPc2RobotMsg(
        verifier,  values->Get(i), types->GetEnum<Pc2RobotMsg>(i))) {
      return false;
    }
  }
  return true;
}

inline bool VerifyRobot2PcMsg(::flatbuffers::Verifier &verifier, const void *obj, Robot2PcMsg type) {
  switch (type) {
    case Robot2PcMsg_NONE: {
      return true;
    }
    case Robot2PcMsg_SensorData: {
      auto ptr = reinterpret_cast<const udp_communication::SensorData *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Robot2PcMsg_StatusReport: {
      auto ptr = reinterpret_cast<const udp_communication::StatusReport *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyRobot2PcMsgVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyRobot2PcMsg(
        verifier,  values->Get(i), types->GetEnum<Robot2PcMsg>(i))) {
      return false;
    }
  }
  return true;
}

inline const udp_communication::Robot2PcWrapper *GetRobot2PcWrapper(const void *buf) {
  return ::flatbuffers::GetRoot<udp_communication::Robot2PcWrapper>(buf);
}

inline const udp_communication::Robot2PcWrapper *GetSizePrefixedRobot2PcWrapper(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<udp_communication::Robot2PcWrapper>(buf);
}

inline bool VerifyRobot2PcWrapperBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<udp_communication::Robot2PcWrapper>(nullptr);
}

inline bool VerifySizePrefixedRobot2PcWrapperBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<udp_communication::Robot2PcWrapper>(nullptr);
}

inline void FinishRobot2PcWrapperBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<udp_communication::Robot2PcWrapper> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedRobot2PcWrapperBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<udp_communication::Robot2PcWrapper> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace udp_communication

#endif  // FLATBUFFERS_GENERATED_UDPMESSAGES_UDP_COMMUNICATION_H_
